name: Github Actions build  

on: [push, pull_request]

jobs:
  tests: build
   strategy:
      matrix:
        os: [  macos-latest ]
        smalltalk:
          - Pharo64-8.0
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./coverage/lcov.info
            flag-name: "Unit"
        